## GBM Vs XGBM Scripting

### 1.Import Libraries:

In [3]:
import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_score,recall_score

### 2.Import Dataset

In [17]:
breast_cancer_data = load_breast_cancer()
breast_cancer_data_df = pd.DataFrame(breast_cancer_data.data,columns=breast_cancer_data.feature_names)
breast_cancer_data_df["Target"] = breast_cancer_data.target
breast_cancer_data_df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

### 3. Data cleaning -- Ntg to clean

### 4. Data Understanding

In [18]:
breast_cancer_data_df.shape

(569, 31)

In [19]:
breast_cancer_data_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [20]:
breast_cancer_data_df.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [21]:
breast_cancer_data_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int64
dtype: object

### 5.Data preparation

In [22]:
X = breast_cancer_data_df.drop("Target",axis=1)

In [24]:
std_scaler = StandardScaler()
scaled_X = pd.DataFrame(std_scaler.fit_transform(X))
scaled_X

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,...,1.511870,-0.023974,1.347475,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,...,-0.281464,0.133984,-0.249939,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,...,1.298575,-1.466770,1.338539,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,2.110995,0.721473,2.060786,2.343856,1.041842,0.219060,1.947285,2.320965,-0.312589,-0.931027,...,1.901185,0.117700,1.752563,2.015301,0.378365,-0.273318,0.664512,1.629151,-1.360158,-0.709091
565,1.704854,2.085134,1.615931,1.723842,0.102458,-0.017833,0.693043,1.263669,-0.217664,-1.058611,...,1.536720,2.047399,1.421940,1.494959,-0.691230,-0.394820,0.236573,0.733827,-0.531855,-0.973978
566,0.702284,2.045574,0.672676,0.577953,-0.840484,-0.038680,0.046588,0.105777,-0.809117,-0.895587,...,0.561361,1.374854,0.579001,0.427906,-0.809587,0.350735,0.326767,0.414069,-1.104549,-0.318409
567,1.838341,2.336457,1.982524,1.735218,1.525767,3.272144,3.296944,2.658866,2.137194,1.043695,...,1.961239,2.237926,2.303601,1.653171,1.430427,3.904848,3.197605,2.289985,1.919083,2.219635
568,-1.808401,1.221792,-1.814389,-1.347789,-3.112085,-1.150752,-1.114873,-1.261820,-0.820070,-0.561032,...,-1.410893,0.764190,-1.432735,-1.075813,-1.859019,-1.207552,-1.305831,-1.745063,-0.048138,-0.751207

In [26]:
y = breast_cancer_data_df.Target
pd.DataFrame(y)

     Target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

### 6.Model Building

#### Gradient boostin model

In [27]:
from sklearn.ensemble import GradientBoostingClassifier

In [67]:
start_time = datetime.now()
gb_model = GradientBoostingClassifier(n_estimators=100,max_depth=3)
end_time = datetime.now()
print("Time Taken to Train the Algorithm:", end_time -  start_time)

Time Taken to Train the Algorithm: 0:00:00.012002

#### Train test model

In [32]:
X_train,X_test,y_train,y_test = train_test_split(scaled_X,y, test_size=0.20,random_state=123,shuffle=True,stratify=y)

In [38]:
# Training samples
X_train.shape,y_train.shape

((455, 30), (455,))

In [37]:
#Testing samples
X_test.shape,y_test.shape

((114, 30), (114,))

### 7.Model Training

In [39]:
gb_model.fit(scaled_X,y)

GradientBoostingClassifier()

### 8.Model Testing

#### Training data

In [41]:
y_train_pred = gb_model.predict(X_train)
y_train_pred

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

#### Tesing data

In [42]:
y_test_pred = gb_model.predict(X_test)
y_test_pred

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1])

### 9.Model Evaluation

#### Training data

In [51]:
print("Classification Report:\n",classification_report(y_train,y_train_pred))
print("confusion Matrix: " ,confusion_matrix(y_train,y_train_pred))
print("Accuracy score:" ,accuracy_score(y_train,y_train_pred))
print("Precision score:" ,precision_score(y_train,y_train_pred))
print("Recall score:" ,recall_score(y_train,y_train_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       170
           1       1.00      1.00      1.00       285

    accuracy                           1.00       455
   macro avg       1.00      1.00      1.00       455
weighted avg       1.00      1.00      1.00       455

confusion Matrix:  [[170   0]
 [  0 285]]
Accuracy score: 1.0
Precision score: 1.0
Recall score: 1.0

#### Testing data

In [52]:
print("Classification Report:\n",classification_report(y_test,y_test_pred))
print("confusion Matrix: " ,confusion_matrix(y_test,y_test_pred))
print("Accuracy score:" ,accuracy_score(y_test,y_test_pred))
print("Precision score:" ,precision_score(y_test,y_test_pred))
print("Recall score:" ,recall_score(y_test,y_test_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       1.00      1.00      1.00        72

    accuracy                           1.00       114
   macro avg       1.00      1.00      1.00       114
weighted avg       1.00      1.00      1.00       114

confusion Matrix:  [[42  0]
 [ 0 72]]
Accuracy score: 1.0
Precision score: 1.0
Recall score: 1.0

## Extreme gradient boosting

In [53]:
from datetime import datetime

In [54]:
!pip install xgboost

Collecting xgboost

[notice] A new release of pip is available: 26.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\aishwarya\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\aishwarya\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
    --------------------------------------- 1.3/101.7 MB 4.0 MB/s eta 0:00:26
    --------------------------------------- 2.4/101.7 MB 4.2 MB/s eta 0:00:24
   - -------------------------------------- 3.1/101.7 MB 4.1 MB/s eta 0:00:25
   - -------------------------------------- 3.9/101.7 MB 4.0 MB/s eta 0:00:25
   - -------------------------------------- 4.5/101.7 MB 3.7 MB/s eta 0:00:27
   - -------------------------------------- 4.7/101.7 MB 3.5 MB/s eta 0:00:28
   -- ------------------------------------- 5.5/101.7 MB 3.5 MB/s eta 0:00:28
   -- ------------------------------------- 6.3/101.7 MB 3.4 MB/s eta 0:00:29
   -- ------------------------------------- 7.1/101.7 MB 3.4 MB/s eta 0:00:28
   -- ------------------------------------- 7.6/101.7 MB 3.4 MB/s eta 0:00:29
   --- ------------------------------------ 8.4/101.7 MB 3.4 MB/s eta 0:00:28
   --- ------------------------------------ 9.2/101.7 MB 3.4 MB/s eta 0:00:28
   --- ------------------------------------ 10.0/101.7 MB 3.4 MB/s eta 0:00:28
   ---- ----------------------------------- 10.7/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 11.5/101.7 MB 3.4 MB/s eta 0:00:27
   ---- ----------------------------------- 12.1/101.7 MB 3.3 MB/s eta 0:00:27
   ----- ---------------------------------- 12.8/101.7 MB 3.4 MB/s eta 0:00:27
   ----- ---------------------------------- 13.4/101.7 MB 3.4 MB/s eta 0:00:27
   ----- ---------------------------------- 14.2/101.7 MB 3.4 MB/s eta 0:00:26
   ----- ---------------------------------- 14.9/101.7 MB 3.4 MB/s eta 0:00:26
   ------ --------------------------------- 16.0/101.7 MB 3.4 MB/s eta 0:00:25
   ------ --------------------------------- 17.0/101.7 MB 3.5 MB/s eta 0:00:25
   ------- -------------------------------- 17.8/101.7 MB 3.5 MB/s eta 0:00:24
   ------- -------------------------------- 18.4/101.7 MB 3.5 MB/s eta 0:00:25
   ------- -------------------------------- 18.9/101.7 MB 3.4 MB/s eta 0:00:25
   ------- -------------------------------- 19.4/101.7 MB 3.4 MB/s eta 0:00:25
   ------- -------------------------------- 20.2/101.7 MB 3.4 MB/s eta 0:00:24
   -------- ------------------------------- 20.7/101.7 MB 3.4 MB/s eta 0:00:24
   -------- ------------------------------- 21.2/101.7 MB 3.4 MB/s eta 0:00:24
   -------- ------------------------------- 22.0/101.7 MB 3.4 MB/s eta 0:00:24
   -------- ------------------------------- 22.5/101.7 MB 3.3 MB/s eta 0:00:24
   --------- ------------------------------ 23.1/101.7 MB 3.3 MB/s eta 0:00:24
   --------- ------------------------------ 23.6/101.7 MB 3.3 MB/s eta 0:00:25
   --------- ------------------------------ 24.1/101.7 MB 3.2 MB/s eta 0:00:25
   --------- ------------------------------ 24.9/101.7 MB 3.2 MB/s eta 0:00:24
   ---------- ----------------------------- 25.7/101.7 MB 3.2 MB/s eta 0:00:24
   ---------- ----------------------------- 26.5/101.7 MB 3.2 MB/s eta 0:00:24
   ---------- ----------------------------- 27.3/101.7 MB 3.2 MB/s eta 0:00:23
   ----------- ---------------------------- 28.0/101.7 MB 3.3 MB/s eta 0:00:23
   ----------- ---------------------------- 28.8/101.7 MB 3.3 MB/s eta 0:00:23
   ----------- ---------------------------- 29.9/101.7 MB 3.3 MB/s eta 0:00:22
   ----------- ---------------------------- 30.4/101.7 MB 3.3 MB/s eta 0:00:22
   ------------ --------------------------- 30.9/101.7 MB 3.3 MB/s eta 0:00:22
   ------------ --------------------------- 31.5/101.7 MB 3.3 MB/s eta 0:00:22
   ------------ --------------------------- 32.2/101.7 MB 3.2 MB/s eta 0:00:22
   ------------ --------------------------- 32.8/101.7 MB 3.3 MB/s eta 0:00:22
   ------------- -------------------------- 33.3/101.7 MB 3.2 MB/s eta 0:00:22
   ------------- -------------------------- 34.3/101.7 MB 3.2 MB/s eta 0:00:21
   ------------- -------------------------- 34.9/101.7 MB 3.2 MB/s eta 0:00:21
   -------------- ------------------------- 35.7/101.7 MB 3.3 MB/s eta 0:00:21
   -------------- ------------------------- 36.4/101.7 MB 3.2 MB/s eta 0:00:21
   -------------- ------------------------- 37.0/101.7 MB 3.2 MB/s eta 0:00:21
   -------------- ------------------------- 37.7/101.7 MB 3.2 MB/s eta 0:00:20
   --------------- ------------------------ 38.5/101.7 MB 3.2 MB/s eta 0:00:20
   --------------- ------------------------ 39.1/101.7 MB 3.3 MB/s eta 0:00:20
   --------------- ------------------------ 39.8/101.7 MB 3.3 MB/s eta 0:00:20
   --------------- ------------------------ 40.6/101.7 MB 3.3 MB/s eta 0:00:19
   ---------------- ----------------------- 41.4/101.7 MB 3.3 MB/s eta 0:00:19
   ---------------- ----------------------- 42.2/101.7 MB 3.3 MB/s eta 0:00:19
   ---------------- ----------------------- 43.0/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 43.8/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 44.8/101.7 MB 3.3 MB/s eta 0:00:18
   ----------------- ---------------------- 45.6/101.7 MB 3.3 MB/s eta 0:00:17
   ------------------ --------------------- 46.4/101.7 MB 3.3 MB/s eta 0:00:17
   ------------------ --------------------- 47.2/101.7 MB 3.3 MB/s eta 0:00:17
   ------------------ --------------------- 48.0/101.7 MB 3.3 MB/s eta 0:00:17
   ------------------- -------------------- 48.8/101.7 MB 3.3 MB/s eta 0:00:16
   ------------------- -------------------- 49.5/101.7 MB 3.3 MB/s eta 0:00:16
   ------------------- -------------------- 50.3/101.7 MB 3.3 MB/s eta 0:00:16
   -------------------- ------------------- 51.1/101.7 MB 3.3 MB/s eta 0:00:16
   -------------------- ------------------- 51.9/101.7 MB 3.3 MB/s eta 0:00:15
   -------------------- ------------------- 52.7/101.7 MB 3.3 MB/s eta 0:00:15
   -------------------- ------------------- 53.2/101.7 MB 3.3 MB/s eta 0:00:15
   --------------------- ------------------ 54.0/101.7 MB 3.3 MB/s eta 0:00:15
   --------------------- ------------------ 54.8/101.7 MB 3.3 MB/s eta 0:00:15
   --------------------- ------------------ 55.6/101.7 MB 3.3 MB/s eta 0:00:14
   ---------------------- ----------------- 56.4/101.7 MB 3.3 MB/s eta 0:00:14
   ---------------------- ----------------- 57.1/101.7 MB 3.3 MB/s eta 0:00:14
   ---------------------- ----------------- 57.9/101.7 MB 3.3 MB/s eta 0:00:14
   ----------------------- ---------------- 58.7/101.7 MB 3.3 MB/s eta 0:00:13
   ----------------------- ---------------- 59.2/101.7 MB 3.3 MB/s eta 0:00:13
   ----------------------- ---------------- 59.8/101.7 MB 3.3 MB/s eta 0:00:13
   ----------------------- ---------------- 60.6/101.7 MB 3.3 MB/s eta 0:00:13
   ------------------------ --------------- 61.3/101.7 MB 3.3 MB/s eta 0:00:13
   ------------------------ --------------- 62.1/101.7 MB 3.3 MB/s eta 0:00:12
   ------------------------ --------------- 62.9/101.7 MB 3.4 MB/s eta 0:00:12
   ------------------------- -------------- 64.0/101.7 MB 3.4 MB/s eta 0:00:12
   ------------------------- -------------- 64.7/101.7 MB 3.4 MB/s eta 0:00:11
   ------------------------- -------------- 65.8/101.7 MB 3.4 MB/s eta 0:00:11
   -------------------------- ------------- 66.6/101.7 MB 3.4 MB/s eta 0:00:11
   -------------------------- ------------- 67.1/101.7 MB 3.4 MB/s eta 0:00:11
   -------------------------- ------------- 67.9/101.7 MB 3.4 MB/s eta 0:00:10
   --------------------------- ------------ 68.7/101.7 MB 3.4 MB/s eta 0:00:10
   --------------------------- ------------ 69.5/101.7 MB 3.4 MB/s eta 0:00:10
   --------------------------- ------------ 70.3/101.7 MB 3.4 MB/s eta 0:00:10
   --------------------------- ------------ 71.0/101.7 MB 3.4 MB/s eta 0:00:10
   ---------------------------- ----------- 71.8/101.7 MB 3.4 MB/s eta 0:00:09
   ---------------------------- ----------- 72.6/101.7 MB 3.4 MB/s eta 0:00:09
   ---------------------------- ----------- 73.1/101.7 MB 3.4 MB/s eta 0:00:09
   ----------------------------- ---------- 73.9/101.7 MB 3.4 MB/s eta 0:00:09
   ----------------------------- ---------- 75.0/101.7 MB 3.4 MB/s eta 0:00:08
   ----------------------------- ---------- 75.8/101.7 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 76.5/101.7 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 77.6/101.7 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 78.1/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 78.9/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 79.7/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 80.7/101.7 MB 3.4 MB/s eta 0:00:07
   -------------------------------- ------- 81.5/101.7 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 82.3/101.7 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 82.8/101.7 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 83.6/101.7 MB 3.4 MB/s eta 0:00:06
   --------------------------------- ------ 84.7/101.7 MB 3.4 MB/s eta 0:00:05
   --------------------------------- ------ 85.7/101.7 MB 3.5 MB/s eta 0:00:05
   ---------------------------------- ----- 86.5/101.7 MB 3.5 MB/s eta 0:00:05
   ---------------------------------- ----- 87.0/101.7 MB 3.5 MB/s eta 0:00:05
   ---------------------------------- ----- 87.6/101.7 MB 3.5 MB/s eta 0:00:05
   ---------------------------------- ----- 87.8/101.7 MB 3.4 MB/s eta 0:00:05
   ---------------------------------- ----- 88.1/101.7 MB 3.4 MB/s eta 0:00:04
   ---------------------------------- ----- 88.6/101.7 MB 3.4 MB/s eta 0:00:04
   ---------------------------------- ----- 88.9/101.7 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 89.4/101.7 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 89.9/101.7 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 90.2/101.7 MB 3.3 MB/s eta 0:00:04
   ----------------------------------- ---- 90.7/101.7 MB 3.3 MB/s eta 0:00:04
   ----------------------------------- ---- 91.2/101.7 MB 3.3 MB/s eta 0:00:04
   ------------------------------------ --- 91.8/101.7 MB 3.3 MB/s eta 0:00:03
   ------------------------------------ --- 92.3/101.7 MB 3.3 MB/s eta 0:00:03
   ------------------------------------ --- 93.1/101.7 MB 3.3 MB/s eta 0:00:03
   ------------------------------------ --- 93.6/101.7 MB 3.3 MB/s eta 0:00:03
   ------------------------------------- -- 94.4/101.7 MB 3.3 MB/s eta 0:00:03
   ------------------------------------- -- 95.2/101.7 MB 3.3 MB/s eta 0:00:02
   ------------------------------------- -- 95.9/101.7 MB 3.3 MB/s eta 0:00:02
   ------------------------------------- -- 96.5/101.7 MB 3.3 MB/s eta 0:00:02
   -------------------------------------- - 97.3/101.7 MB 3.3 MB/s eta 0:00:02
   -------------------------------------- - 98.0/101.7 MB 3.3 MB/s eta 0:00:02
   -------------------------------------- - 98.6/101.7 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 99.1/101.7 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  99.9/101.7 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  101.2/101.7 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 3.3 MB/s  0:00:30
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

In [55]:
import xgboost as xgb

In [66]:
start_time = datetime.now()
xgb_model  = xgb.XGBClassifier(max_depth = 3,n_estimators = 40,learning_rate = 0.008,gamma = 1.9)
end_time = datetime.now()
print("Time Taken to Train the Algorithm:", end_time -  start_time)

Time Taken to Train the Algorithm: 0:00:00.001002

In [62]:
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=1.9, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.008, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=40,
              n_jobs=None, num_parallel_tree=None, ...)

In [63]:
y_train_pred = xgb_model.predict(X_train)
y_train_pred
print("Classification Report:\n",classification_report(y_train,y_train_pred))
print("confusion Matrix: " ,confusion_matrix(y_train,y_train_pred))
print("Accuracy score:" ,accuracy_score(y_train,y_train_pred))
print("Precision score:" ,precision_score(y_train,y_train_pred))
print("Recall score:" ,recall_score(y_train,y_train_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.81      0.90       170
           1       0.90      1.00      0.95       285

    accuracy                           0.93       455
   macro avg       0.95      0.91      0.92       455
weighted avg       0.94      0.93      0.93       455

confusion Matrix:  [[138  32]
 [  0 285]]
Accuracy score: 0.9296703296703297
Precision score: 0.8990536277602523
Recall score: 1.0

In [64]:
y_test_pred = xgb_model.predict(X_test)
y_test_pred
print("Classification Report:\n",classification_report(y_test,y_test_pred))
print("confusion Matrix: " ,confusion_matrix(y_test,y_test_pred))
print("Accuracy score:" ,accuracy_score(y_test,y_test_pred))
print("Precision score:" ,precision_score(y_test,y_test_pred))
print("Recall score:" ,recall_score(y_test,y_test_pred))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.88      0.94        42
           1       0.94      1.00      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.94      0.95       114
weighted avg       0.96      0.96      0.96       114

confusion Matrix:  [[37  5]
 [ 0 72]]
Accuracy score: 0.956140350877193
Precision score: 0.935064935064935
Recall score: 1.0